# Generated by Django 4.2.1 on 2023-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phn_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
