# Generated by Django 4.2.1 on 2023-05-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_user_phn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=models.CharField(max_length=30), max_length=100),
        ),
    ]
