# Generated by Django 4.2.1 on 2023-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_stars',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
